export const students = [
  {
    city: "Fushë-Muhurr",
    company: "Yadel",
    email: "iorton0@imdb.com",
    firstName: "Ingaberg",
    grades: ["78", "100", "92", "86", "89", "88", "91", "87"],
    id: "1",
    lastName: "Orton",
    pic: "https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/voluptasdictablanditiis.jpg",
    skill: "Oracle",
  },
  {
    city: "Sanghan",
    company: "Avamm",
    email: "cboards1@weibo.com",
    firstName: "Clarke",
    grades: ["75", "89", "95", "93", "99", "82", "89", "76"],
    id: "2",
    lastName: "Boards",
    pic: "https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/voluptasautreprehenderit.jpg",
    skill: "Sports",
  },
  {
    city: "Kugesi",
    company: "Skalith",
    email: "lromanet2@wired.com",
    firstName: "Laurens",
    grades: ["88", "90", "79", "82", "81", "99", "94", "73"],
    id: "3",
    lastName: "Romanet",
    pic: "https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/aspernaturnonsapiente.jpg",
    skill: "Employee Handbooks",
  },
  {
    city: "Krajan",
    company: "Mybuzz",
    email: "bskitt3@aboutads.info",
    firstName: "Berti",
    grades: ["88", "93", "92", "81", "95", "98", "77", "94"],
    id: "4",
    lastName: "Skitt",
    pic: "https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/autautdeserunt.jpg",
    skill: "Nutrition Education",
  },
  {
    city: "Huiqi",
    company: "Avavee",
    email: "msummerley4@craigslist.org",
    firstName: "Mureil",
    grades: ["71", "81", "72", "92", "79", "82", "91", "90"],
    id: "5",
    lastName: "Summerley",
    pic: "https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/consequaturdelectusquis.jpg",
    skill: "ISO 14971",
  },
];
